# This workflow should download the latest antiword zip, and compare the previous hash 
# with the current hash. 

name: check-antiword-hash

on:
  schedule:
      - cron: "0 0 * * *"
  
  workflow_dispatch:
 
jobs:
  antiword_hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Check Antiword Hash
        run: |
          wget https://cran.r-project.org/bin/windows/contrib/4.4/antiword_1.3.4.zip
          PREVIOUS_HASH=$(cat /home/runner/work/bitcurator-win-salt/bitcurator-win-salt/bitcurator/standalones/antiword.sls | grep "set hash" | awk -F\' '{print tolower($2)}')
          CURRENT_HASH=$(sha256sum antiword_1.3.4.zip | awk '{print $1}')
          if [[ "$PREVIOUS_HASH" != "$CURRENT_HASH" ]]; then echo "HASH UPDATED - $CURRENT_HASH" && exit 1; else echo "No hash changes" && exit 0; fi
